name: Testy API (Pytest)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run tests and generate HTML report
        run: |
          python -m pytest --html=report.html --self-contained-html --cov=utils

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: Test_Report
          path: report.html
